#!/usr/bin/env python3
"""
Generate improved Paper 2 figures and numerical summaries.

This plotting script does not rerun the simulation or change model outputs.
It reads the Paper 2 CSV files generated by SimulationRunner and improves the
presentation of:

1. Continuous hysteresis:
   - Separates increasing-target and decreasing-target branches.
   - Bins noisy coherence-gap values by target entropy.
   - Preserves causal RF/DF comparison in adaptive gain.

2. Explicit disturbance-pulse recovery:
   - Marks the configured pulse interval.
   - Shows faint raw trajectories plus smoothed diagnostic trajectories.
   - Writes descriptive pulse/recovery summary statistics.

3. Dwell behavior:
   - Shows mean dwell time on a logarithmic scale because LOW/MID dwells are
     much shorter than HIGH dwells.
   - Shows regime occupancy fractions separately.
   - Retains interpretation as descriptive until replicate-level confidence
     intervals and theoretically justified thresholds are established.
"""
from __future__ import annotations

import csv
from pathlib import Path
from typing import Iterable

import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[2] / "results" / "paper2"
FIG = ROOT / "figures"
SUMMARY = ROOT / "summary"
FIG.mkdir(parents=True, exist_ok=True)
SUMMARY.mkdir(parents=True, exist_ok=True)

ORDERINGS = [
    ("rf", "Regulation first"),
    ("df", "Disturbance first"),
]
REGIMES = [("LOW", 0), ("MID", 1), ("HIGH", 2)]


def table(folder: str, filename: str) -> np.ndarray:
    path = ROOT / folder / filename
    if not path.exists():
        raise FileNotFoundError(
            f"Required Paper 2 result file not found: {path}\n"
            "Run: bash analysis/scripts/run_paper2.sh run"
        )
    return np.genfromtxt(
        path,
        delimiter=",",
        names=True,
        dtype=None,
        encoding="utf-8",
    )


def write_rows(path: Path, header: Iterable[str], rows: list[list[object]]) -> None:
    with path.open("w", newline="") as stream:
        writer = csv.writer(stream)
        writer.writerow(list(header))
        writer.writerows(rows)


def moving_mean(y: np.ndarray, window: int) -> np.ndarray:
    """Centered moving average with edge padding."""
    y = np.asarray(y, dtype=float)
    window = max(1, int(window))
    if window <= 1 or y.size < 3:
        return y.copy()
    if window % 2 == 0:
        window += 1
    pad = window // 2
    padded = np.pad(y, pad, mode="edge")
    kernel = np.ones(window, dtype=float) / window
    return np.convolve(padded, kernel, mode="valid")


def window_for_time(t: np.ndarray, width_time: float) -> int:
    if len(t) < 2:
        return 1
    dt = float(np.median(np.diff(t)))
    if dt <= 0.0:
        return 1
    return max(3, int(round(width_time / dt)))


def binned_branch(
    x: np.ndarray,
    y: np.ndarray,
    direction: np.ndarray,
    branch: str,
    edges: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    mask = np.asarray(direction == branch)
    xb = np.asarray(x[mask], dtype=float)
    yb = np.asarray(y[mask], dtype=float)
    centers = 0.5 * (edges[:-1] + edges[1:])
    means = np.full(centers.shape, np.nan, dtype=float)
    stds = np.full(centers.shape, np.nan, dtype=float)

    for index in range(len(centers)):
        if index == len(centers) - 1:
            in_bin = (xb >= edges[index]) & (xb <= edges[index + 1])
        else:
            in_bin = (xb >= edges[index]) & (xb < edges[index + 1])
        if np.any(in_bin):
            means[index] = np.mean(yb[in_bin])
            stds[index] = np.std(yb[in_bin])
    return centers, means, stds


def aligned_valid(*ys: np.ndarray) -> np.ndarray:
    mask = np.ones(len(ys[0]), dtype=bool)
    for y in ys:
        mask &= np.isfinite(y)
    return mask


def hysteresis_branch_figures() -> None:
    loops = {
        tag: table(f"{tag}_hysteresis", "hysteresis_loop.csv")
        for tag, _ in ORDERINGS
    }

    all_targets = np.concatenate(
        [np.asarray(loop["targetEntropy"], dtype=float) for loop in loops.values()]
    )
    edges = np.linspace(float(np.min(all_targets)), float(np.max(all_targets)), 46)
    branch_rows: list[list[object]] = []

    # Binned coherence-gap loop: raw per-step data were too noisy to interpret.
    fig, ax = plt.subplots(figsize=(8.0, 5.2))
    line_colors: dict[str, str] = {}
    for tag, label in ORDERINGS:
        loop = loops[tag]
        center_up, mean_up, std_up = binned_branch(
            loop["targetEntropy"], loop["dC"], loop["direction"], "up", edges
        )
        center_down, mean_down, std_down = binned_branch(
            loop["targetEntropy"], loop["dC"], loop["direction"], "down", edges
        )
        valid_up = np.isfinite(mean_up)
        line = ax.plot(
            center_up[valid_up], mean_up[valid_up],
            linestyle="-", linewidth=2.1,
            label=f"{label}: increasing target"
        )[0]
        line_colors[tag] = line.get_color()
        valid_down = np.isfinite(mean_down)
        ax.plot(
            center_down[valid_down], mean_down[valid_down],
            linestyle="--", linewidth=2.1, color=line_colors[tag],
            label=f"{label}: decreasing target"
        )

        common = aligned_valid(mean_up, mean_down)
        signed_area = float(np.trapezoid(mean_down[common] - mean_up[common], center_up[common]))
        mean_sep = float(np.mean(mean_down[common] - mean_up[common]))
        branch_rows.append([tag, "coherence_gap", signed_area, mean_sep])

    ax.set_xlabel(r"Target entropy $S^*$")
    ax.set_ylabel(r"Binned mean coherence gap $\langle\Delta C\rangle$")
    ax.set_title("Continuous target-ramp hysteresis: coherence-gap response")
    ax.legend(fontsize=8.8, ncol=2, loc="upper center", bbox_to_anchor=(0.5, -0.16))
    fig.tight_layout()
    fig.savefig(FIG / "paper2_hysteresis_coherence_binned_RF_DF.png", dpi=300)
    plt.close(fig)

    # Regulation-gain loop: show branches explicitly.
    fig, ax = plt.subplots(figsize=(8.0, 5.2))
    line_colors = {}
    for tag, label in ORDERINGS:
        loop = loops[tag]
        center_up, mean_up, _ = binned_branch(
            loop["targetEntropy"], loop["mu"], loop["direction"], "up", edges
        )
        center_down, mean_down, _ = binned_branch(
            loop["targetEntropy"], loop["mu"], loop["direction"], "down", edges
        )
        valid_up = np.isfinite(mean_up)
        line = ax.plot(
            center_up[valid_up], mean_up[valid_up],
            linestyle="-", linewidth=2.2,
            label=f"{label}: increasing target"
        )[0]
        line_colors[tag] = line.get_color()
        valid_down = np.isfinite(mean_down)
        ax.plot(
            center_down[valid_down], mean_down[valid_down],
            linestyle="--", linewidth=2.2, color=line_colors[tag],
            label=f"{label}: decreasing target"
        )

        common = aligned_valid(mean_up, mean_down)
        signed_area = float(np.trapezoid(mean_down[common] - mean_up[common], center_up[common]))
        mean_sep = float(np.mean(mean_down[common] - mean_up[common]))
        branch_rows.append([tag, "regulation_gain", signed_area, mean_sep])

    ax.set_xlabel(r"Target entropy $S^*$")
    ax.set_ylabel(r"Binned mean regulation gain $\langle\mu\rangle$")
    ax.set_title("Carryover in adaptive regulation under continuous target ramp")
    ax.legend(fontsize=8.8, ncol=2)
    fig.tight_layout()
    fig.savefig(FIG / "paper2_hysteresis_mu_branches_RF_DF.png", dpi=300)
    plt.close(fig)

    write_rows(
        SUMMARY / "hysteresis_branch_summary.csv",
        ["ordering", "observable", "signed_area_down_minus_up", "mean_down_minus_up"],
        branch_rows,
    )


def intervention_recovery_figure() -> None:
    series = {}
    pulse_starts = []
    pulse_ends = []

    for tag, _ in ORDERINGS:
        coherence = table(f"{tag}_intervention", "coherence.csv")
        flag = table(f"{tag}_intervention", "interventionFlag.csv")
        t = np.asarray(coherence["t"], dtype=float)
        d_c = np.asarray(coherence["dC"], dtype=float)
        active = np.asarray(flag["interventionFlag"], dtype=float) > 0.5

        if not np.any(active):
            raise ValueError(f"No active intervention samples found for {tag}.")
        pulse_starts.append(float(t[active][0]))
        pulse_ends.append(float(t[active][-1]))

        smooth_window = window_for_time(t, width_time=1.0)
        series[tag] = (t, d_c, moving_mean(d_c, smooth_window), active, smooth_window)

    pulse_start = min(pulse_starts)
    pulse_end = max(pulse_ends)

    fig, ax = plt.subplots(figsize=(8.5, 5.1))
    ax.axvspan(pulse_start, pulse_end, alpha=0.15, label="Explicit disturbance pulse")

    recovery_rows: list[list[object]] = []
    for tag, label in ORDERINGS:
        t, d_c, smooth, active, smooth_window = series[tag]
        before = t < pulse_start
        during = active
        after = t > pulse_end
        follow_end = pulse_end + (pulse_end - pulse_start)
        recovery_window = after & (t <= follow_end)

        baseline_mean = float(np.mean(d_c[before]))
        baseline_std = float(np.std(d_c[before]))
        peak_during = float(np.max(d_c[during]))
        mean_during = float(np.mean(d_c[during]))

        positive_during = np.maximum(d_c[during] - baseline_mean, 0.0)
        positive_recovery = np.maximum(d_c[recovery_window] - baseline_mean, 0.0)
        pulse_auc = float(np.trapezoid(positive_during, t[during]))
        recovery_auc = float(np.trapezoid(positive_recovery, t[recovery_window]))

        threshold = baseline_mean + 2.0 * baseline_std
        post_idx = np.flatnonzero(after)
        recovery_time = np.nan
        stable_n = max(3, window_for_time(t, width_time=1.0))
        for pos in post_idx:
            end = min(len(t), pos + stable_n)
            if end - pos == stable_n and np.all(smooth[pos:end] <= threshold):
                recovery_time = float(t[pos] - pulse_end)
                break

        recovery_rows.append([
            tag, pulse_start, pulse_end, baseline_mean, baseline_std,
            mean_during, peak_during, pulse_auc, recovery_auc, recovery_time,
            smooth_window,
        ])

        raw_line = ax.plot(t, d_c, linewidth=0.55, alpha=0.13)[0]
        ax.plot(
            t, smooth, linewidth=2.0, color=raw_line.get_color(),
            label=f"{label}: smoothed"
        )

    ax.set_xlabel("Time")
    ax.set_ylabel(r"Coherence gap $\Delta C(t)$")
    ax.set_title("Recovery following explicit disturbance pulse")
    ax.legend(fontsize=9)
    fig.tight_layout()
    fig.savefig(FIG / "paper2_intervention_recovery_smoothed_RF_DF.png", dpi=300)
    plt.close(fig)

    write_rows(
        SUMMARY / "intervention_recovery_summary.csv",
        [
            "ordering", "pulse_start", "pulse_end",
            "pre_pulse_mean_dC", "pre_pulse_std_dC",
            "pulse_mean_dC", "pulse_peak_dC",
            "positive_pulse_auc", "positive_recovery_auc",
            "diagnostic_recovery_time", "smoothing_window_samples",
        ],
        recovery_rows,
    )


def dwell_figures() -> None:
    summary = {
        tag: table(f"{tag}_dwell", "dwell_summary.csv")
        for tag, _ in ORDERINGS
    }
    labels = [name for name, _ in REGIMES]
    x = np.arange(len(labels), dtype=float)
    width = 0.36

    means: dict[str, dict[str, float]] = {}
    counts: dict[str, dict[str, int]] = {}
    occupancy: dict[str, dict[str, float]] = {}

    for tag, _ in ORDERINGS:
        means[tag] = {
            str(r): float(m)
            for r, m in zip(summary[tag]["regime"], summary[tag]["meanDwellTime"])
        }
        counts[tag] = {
            str(r): int(n)
            for r, n in zip(summary[tag]["regime"], summary[tag]["count"])
        }

        regime_series = table(f"{tag}_dwell", "regimeLabel.csv")
        observed = np.asarray(regime_series["label"], dtype=int)
        occupancy[tag] = {
            name: float(np.mean(observed == code))
            for name, code in REGIMES
        }

    # Log scale allows all regime means to remain visible.
    fig, ax = plt.subplots(figsize=(7.4, 5.0))
    left = ax.bar(
        x - width / 2,
        [means["rf"][name] for name in labels],
        width,
        label="Regulation first"
    )
    right = ax.bar(
        x + width / 2,
        [means["df"][name] for name in labels],
        width,
        label="Disturbance first"
    )
    ax.set_yscale("log")
    ax.set_xticks(x, labels)
    ax.set_xlabel("Coherence-gap regime")
    ax.set_ylabel("Mean dwell time (log scale)")
    ax.set_title("Dwell-time comparison by coherence-gap regime")
    ax.legend()

    for bars, tag in [(left, "rf"), (right, "df")]:
        for bar, regime in zip(bars, labels):
            value = bar.get_height()
            ax.text(
                bar.get_x() + bar.get_width() / 2,
                value * 1.10,
                f"n={counts[tag][regime]}",
                ha="center", va="bottom", fontsize=8
            )

    fig.tight_layout()
    fig.savefig(FIG / "paper2_dwell_RF_DF_logscale.png", dpi=300)
    plt.close(fig)

    # Occupancy makes it explicit which regime dominates the trace.
    fig, ax = plt.subplots(figsize=(7.4, 5.0))
    ax.bar(
        x - width / 2,
        [occupancy["rf"][name] for name in labels],
        width,
        label="Regulation first"
    )
    ax.bar(
        x + width / 2,
        [occupancy["df"][name] for name in labels],
        width,
        label="Disturbance first"
    )
    ax.set_xticks(x, labels)
    ax.set_xlabel("Coherence-gap regime")
    ax.set_ylabel("Fraction of recorded time")
    ax.set_title("Occupancy of coherence-gap regimes")
    ax.legend()
    fig.tight_layout()
    fig.savefig(FIG / "paper2_regime_occupancy_RF_DF.png", dpi=300)
    plt.close(fig)

    dwell_rows: list[list[object]] = []
    for tag, _ in ORDERINGS:
        for regime in labels:
            dwell_rows.append([
                tag,
                regime,
                counts[tag][regime],
                means[tag][regime],
                occupancy[tag][regime],
            ])
    write_rows(
        SUMMARY / "dwell_and_occupancy_summary.csv",
        ["ordering", "regime", "number_of_dwells", "mean_dwell_time", "time_fraction"],
        dwell_rows,
    )


def main() -> None:
    hysteresis_branch_figures()
    intervention_recovery_figure()
    dwell_figures()
    print(f"Wrote improved Paper 2 figures to {FIG}")
    print(f"Wrote Paper 2 numerical summaries to {SUMMARY}")
    print("Interpretation note: recovery and dwell outputs remain descriptive single-run")
    print("summaries unless the corresponding protocols are rerun over replicate ensembles.")


if __name__ == "__main__":
    main()
