#!/usr/bin/env python3
"""
Paper 2 Figures 4 and 5: quantitative summaries from existing matched-seed
continuous-ramp hysteresis replicate files.

This is a plotting/analysis-only script. It does NOT rerun the Java simulation.

Expected input directories, already generated by the ensemble hysteresis run:

    analysis/results/paper2/rf_hysteresis_ensemble/rep_*/hysteresis_loop.csv
    analysis/results/paper2/df_hysteresis_ensemble/rep_*/hysteresis_loop.csv

Each hysteresis_loop.csv must contain columns:
    direction, targetEntropy, dC, mu

and direction must contain the branch labels:
    up, down

Outputs:
    analysis/results/paper2/figures/paper2_hysteresis_area_summary_RF_DF.png
    analysis/results/paper2/figures/paper2_hysteresis_area_summary_RF_DF.pdf
    analysis/results/paper2/figures/paper2_paired_ordering_difference_RF_DF.png
    analysis/results/paper2/figures/paper2_paired_ordering_difference_RF_DF.pdf

    analysis/results/paper2/summary/paper2_hysteresis_area_per_replicate.csv
    analysis/results/paper2/summary/paper2_hysteresis_area_summary.csv
    analysis/results/paper2/summary/paper2_paired_difference_curves.csv

Usage from the IRAM-Omega-Q project root:

    source .venv/bin/activate
    python3 analysis/scripts/plot_paper2_hysteresis_effect_summaries.py

Optional:

    python3 analysis/scripts/plot_paper2_hysteresis_effect_summaries.py \
        --root analysis/results/paper2 --bins 34
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Iterable

import matplotlib.pyplot as plt
import numpy as np


ORDERINGS = {
    "rf": "Regulation first",
    "df": "Disturbance first",
}
BRANCHES = {
    "up": ("Increasing target", "-"),
    "down": ("Decreasing target", "--"),
}
OBSERVABLES = {
    "mu": (r"Adaptive regulation gain $\mu$", r"$A_{\mu}$",
           r"Paired difference $\mu_{\mathrm{DF}}-\mu_{\mathrm{RF}}$"),
    "dC": (r"Coherence gap $\Delta C$", r"$A_{\Delta C}$",
           r"Paired difference $\Delta C_{\mathrm{DF}}-\Delta C_{\mathrm{RF}}$"),
}


def read_csv(path: Path) -> np.ndarray:
    if not path.exists():
        raise FileNotFoundError(f"Required replicate file not found: {path}")
    data = np.genfromtxt(path, delimiter=",", names=True, dtype=None, encoding="utf-8")
    required = {"direction", "targetEntropy", "mu", "dC"}
    names = set(data.dtype.names or ())
    missing = required - names
    if missing:
        raise ValueError(f"{path} is missing columns: {sorted(missing)}")
    return data


def write_rows(path: Path, header: Iterable[str], rows: Iterable[Iterable[object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as stream:
        writer = csv.writer(stream)
        writer.writerow(list(header))
        writer.writerows(rows)


def discover_pairs(rf_root: Path, df_root: Path) -> list[str]:
    rf = {p.name for p in rf_root.glob("rep_*")
          if (p / "hysteresis_loop.csv").exists()}
    df = {p.name for p in df_root.glob("rep_*")
          if (p / "hysteresis_loop.csv").exists()}
    common = sorted(rf & df)
    if not common:
        raise FileNotFoundError(
            "No matched RF/DF replicate outputs found.\n"
            f"Expected files below:\n  {rf_root}/rep_*/hysteresis_loop.csv\n"
            f"  {df_root}/rep_*/hysteresis_loop.csv\n"
            "First run the existing Paper 2 ensemble hysteresis analysis."
        )
    if rf != df:
        print("Warning: unmatched replicate folders ignored.")
        print("  RF only:", sorted(rf - df))
        print("  DF only:", sorted(df - rf))
    return common


def binned_curve(data: np.ndarray, observable: str, branch: str,
                 edges: np.ndarray) -> np.ndarray:
    directions = np.asarray(data["direction"])
    mask = directions == branch
    x = np.asarray(data["targetEntropy"][mask], dtype=float)
    y = np.asarray(data[observable][mask], dtype=float)
    out = np.full(len(edges) - 1, np.nan)
    for i in range(len(out)):
        in_bin = ((x >= edges[i]) & (x <= edges[i + 1])
                  if i == len(out) - 1
                  else (x >= edges[i]) & (x < edges[i + 1]))
        if np.any(in_bin):
            out[i] = np.mean(y[in_bin])
    return out


def stats(values: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    n = np.sum(np.isfinite(values), axis=0)
    mean = np.nanmean(values, axis=0)
    with np.errstate(invalid="ignore", divide="ignore"):
        sd = np.nanstd(values, axis=0, ddof=1)
        ci95 = 1.96 * sd / np.sqrt(n)
    ci95[n < 2] = np.nan
    return mean, ci95, n


def vector_stats(values: np.ndarray) -> tuple[float, float, float, int]:
    x = np.asarray(values, dtype=float)
    x = x[np.isfinite(x)]
    n = x.size
    if n == 0:
        return np.nan, np.nan, np.nan, 0
    mean = float(np.mean(x))
    if n < 2:
        return mean, np.nan, np.nan, n
    sd = float(np.std(x, ddof=1))
    ci95 = float(1.96 * sd / np.sqrt(n))
    return mean, sd, ci95, n


def integrate_finite(y: np.ndarray, x: np.ndarray) -> float:
    good = np.isfinite(x) & np.isfinite(y)
    if np.sum(good) < 2:
        return np.nan
    if hasattr(np, "trapezoid"):
        return float(np.trapezoid(y[good], x[good]))
    return float(np.trapz(y[good], x[good]))


def build_curves(raw: dict[str, dict[str, np.ndarray]], reps: list[str],
                 edges: np.ndarray) -> dict[str, dict[str, dict[str, np.ndarray]]]:
    curves: dict[str, dict[str, dict[str, np.ndarray]]] = {}
    for ordering in ORDERINGS:
        curves[ordering] = {}
        for observable in OBSERVABLES:
            curves[ordering][observable] = {}
            for branch in BRANCHES:
                curves[ordering][observable][branch] = np.vstack([
                    binned_curve(raw[ordering][rep], observable, branch, edges)
                    for rep in reps
                ])
    return curves


def produce_area_figure(
    curves: dict[str, dict[str, dict[str, np.ndarray]]],
    reps: list[str],
    centers: np.ndarray,
    fig_dir: Path,
    summary_dir: Path,
) -> None:
    per_rep_rows = []
    area: dict[str, dict[str, np.ndarray]] = {obs: {} for obs in OBSERVABLES}

    for observable in OBSERVABLES:
        for ordering in ORDERINGS:
            up = curves[ordering][observable]["up"]
            down = curves[ordering][observable]["down"]
            values = np.asarray([
                integrate_finite(down[i] - up[i], centers)
                for i in range(len(reps))
            ])
            area[observable][ordering] = values
            for rep, value in zip(reps, values):
                per_rep_rows.append([rep, ordering, observable, value])

    write_rows(
        summary_dir / "paper2_hysteresis_area_per_replicate.csv",
        ["replicate", "ordering", "observable",
         "signed_area_integral_down_minus_up"],
        per_rep_rows,
    )

    summary_rows = []
    for observable in OBSERVABLES:
        rf = area[observable]["rf"]
        df = area[observable]["df"]
        for ordering, values in [("rf", rf), ("df", df),
                                 ("paired_df_minus_rf", df - rf)]:
            mean, sd, ci95, n = vector_stats(values)
            summary_rows.append([observable, ordering, n, mean, sd, ci95])

    write_rows(
        summary_dir / "paper2_hysteresis_area_summary.csv",
        ["observable", "comparison", "n", "mean", "sd",
         "ci95_half_width"],
        summary_rows,
    )

    colors = {"rf": "tab:blue", "df": "tab:orange"}
    fig, axes = plt.subplots(1, 2, figsize=(11.2, 5.0))
    rng = np.random.default_rng(24680)

    for ax, observable in zip(axes, ("mu", "dC")):
        rf = area[observable]["rf"]
        df = area[observable]["df"]
        for left, right in zip(rf, df):
            if np.isfinite(left) and np.isfinite(right):
                ax.plot([0, 1], [left, right], linewidth=0.7,
                        alpha=0.28, color="0.45", zorder=1)

        for x, ordering in enumerate(("rf", "df")):
            vals = area[observable][ordering]
            good = np.isfinite(vals)
            jitter = rng.normal(0.0, 0.028, np.sum(good))
            ax.scatter(x + jitter, vals[good], s=17, alpha=0.45,
                       color=colors[ordering], zorder=2)
            mean, _, ci95, _ = vector_stats(vals)
            ax.errorbar(x, mean, yerr=ci95, fmt="o", markersize=8,
                        capsize=5, linewidth=2.0, color=colors[ordering],
                        zorder=3)

        ax.axhline(0.0, color="0.25", linewidth=0.9)
        ax.set_xticks([0, 1], [ORDERINGS["rf"], ORDERINGS["df"]])
        ax.set_title(OBSERVABLES[observable][0])
        ax.set_ylabel(
            OBSERVABLES[observable][1] +
            r"  $=\int(y_{\downarrow}-y_{\uparrow})\,dS^*$"
        )

    fig.suptitle(
        "Paired hysteresis-loop area summary across matched-seed replicates",
        fontsize=14,
    )
    fig.text(
        0.5, -0.015,
        "Points are replicate-level signed areas; large markers show mean "
        "with approximate 95% CI. Positive area means the decreasing-target "
        "branch lies above the increasing-target branch.",
        ha="center", fontsize=9,
    )
    fig.tight_layout()
    for suffix in ("png", "pdf"):
        fig.savefig(fig_dir / f"paper2_hysteresis_area_summary_RF_DF.{suffix}",
                    dpi=300 if suffix == "png" else None,
                    bbox_inches="tight")
    plt.close(fig)


def produce_paired_difference_figure(
    curves: dict[str, dict[str, dict[str, np.ndarray]]],
    centers: np.ndarray,
    fig_dir: Path,
    summary_dir: Path,
) -> None:
    rows = []
    computed = {}
    for observable in OBSERVABLES:
        computed[observable] = {}
        for branch in BRANCHES:
            paired = (curves["df"][observable][branch] -
                      curves["rf"][observable][branch])
            mean, ci95, n = stats(paired)
            computed[observable][branch] = (mean, ci95, n)
            for x, m, c, count in zip(centers, mean, ci95, n):
                rows.append([observable, branch, x, int(count), m, c])

    write_rows(
        summary_dir / "paper2_paired_difference_curves.csv",
        ["observable", "branch", "targetEntropy_bin_center",
         "n_matched_pairs", "mean_df_minus_rf", "ci95_half_width"],
        rows,
    )

    fig, axes = plt.subplots(1, 2, figsize=(11.2, 5.0), sharex=True)
    for ax, observable in zip(axes, ("mu", "dC")):
        for branch, (label, linestyle) in BRANCHES.items():
            mean, ci95, n = computed[observable][branch]
            good = np.isfinite(mean) & (n > 0)
            ci_good = good & np.isfinite(ci95)
            ax.plot(centers[good], mean[good], linestyle=linestyle,
                    linewidth=2.2, label=label)
            if np.any(ci_good):
                ax.fill_between(
                    centers[ci_good],
                    mean[ci_good] - ci95[ci_good],
                    mean[ci_good] + ci95[ci_good],
                    alpha=0.16, linewidth=0,
                )
        ax.axhline(0.0, color="0.25", linewidth=0.9)
        ax.set_xlabel(r"Target entropy $S^*$")
        ax.set_ylabel(OBSERVABLES[observable][2])
        ax.set_title(OBSERVABLES[observable][0])
        ax.legend(fontsize=9)

    fig.suptitle(
        "Paired disturbance-first minus regulation-first differences",
        fontsize=14,
    )
    fig.text(
        0.5, -0.015,
        "Positive adaptive-gain difference denotes greater regulatory demand "
        "under disturbance-first ordering. Bands are approximate 95% CIs "
        "across matched-seed replicate differences.",
        ha="center", fontsize=9,
    )
    fig.tight_layout()
    for suffix in ("png", "pdf"):
        fig.savefig(fig_dir / f"paper2_paired_ordering_difference_RF_DF.{suffix}",
                    dpi=300 if suffix == "png" else None,
                    bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--root", type=Path,
        default=Path("analysis/results/paper2"),
        help="Paper 2 result directory containing RF/DF ensemble folders.",
    )
    parser.add_argument(
        "--bins", type=int, default=34,
        help="Number of S* bins; use the same value as the ensemble hysteresis plot.",
    )
    args = parser.parse_args()

    root = args.root
    rf_root = root / "rf_hysteresis_ensemble"
    df_root = root / "df_hysteresis_ensemble"
    fig_dir = root / "figures"
    summary_dir = root / "summary"
    fig_dir.mkdir(parents=True, exist_ok=True)
    summary_dir.mkdir(parents=True, exist_ok=True)

    reps = discover_pairs(rf_root, df_root)
    print(f"Matched RF/DF hysteresis replicate pairs found: {len(reps)}")

    raw: dict[str, dict[str, np.ndarray]] = {"rf": {}, "df": {}}
    targets = []
    for ordering, folder in (("rf", rf_root), ("df", df_root)):
        for rep in reps:
            data = read_csv(folder / rep / "hysteresis_loop.csv")
            raw[ordering][rep] = data
            targets.append(np.asarray(data["targetEntropy"], dtype=float))

    all_target = np.concatenate(targets)
    edges = np.linspace(np.nanmin(all_target), np.nanmax(all_target), args.bins + 1)
    centers = 0.5 * (edges[:-1] + edges[1:])
    curves = build_curves(raw, reps, edges)

    produce_area_figure(curves, reps, centers, fig_dir, summary_dir)
    produce_paired_difference_figure(curves, centers, fig_dir, summary_dir)

    print(f"Wrote Figure 4: {fig_dir / 'paper2_hysteresis_area_summary_RF_DF.png'}")
    print(f"Wrote Figure 5: {fig_dir / 'paper2_paired_ordering_difference_RF_DF.png'}")
    print(f"Wrote numerical summaries to: {summary_dir}")


if __name__ == "__main__":
    main()
