#!/usr/bin/env python3
"""
Replicate-averaged continuous-hysteresis analysis for Paper 2.

This script reads matched-seed RF/DF HYSTERESIS replicate outputs generated by:

    bash analysis/scripts/run_paper2.sh hysteresis-ensemble 30

No simulation is performed here. For each replicate and each causal ordering,
the continuous triangular target-entropy run is divided into:

    up   : increasing-target branch
    down : decreasing-target branch

Within each replicate, mu(t) and Delta C(t) are binned by target entropy S*.
The resulting branch curves are then averaged across replicates. The figures
display ensemble mean curves with approximate 95% confidence intervals
computed as 1.96 * SEM across replicate-level binned means.

Because RF and DF use matched seeds, the script also exports paired DF-RF
differences in hysteresis-loop area and branch-averaged regulatory demand.
"""
from __future__ import annotations

import csv
from pathlib import Path
from typing import Iterable

import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[2] / "results" / "paper2"
RF_ROOT = ROOT / "rf_hysteresis_ensemble"
DF_ROOT = ROOT / "df_hysteresis_ensemble"
FIG = ROOT / "figures"
SUMMARY = ROOT / "summary"
FIG.mkdir(parents=True, exist_ok=True)
SUMMARY.mkdir(parents=True, exist_ok=True)

ORDERINGS = [
    ("rf", "Regulation first", RF_ROOT),
    ("df", "Disturbance first", DF_ROOT),
]
BRANCHES = [
    ("up", "increasing target", "-"),
    ("down", "decreasing target", "--"),
]
N_BINS = 34


def load_csv(path: Path) -> np.ndarray:
    if not path.exists():
        raise FileNotFoundError(f"Required replicate result missing: {path}")
    return np.genfromtxt(
        path,
        delimiter=",",
        names=True,
        dtype=None,
        encoding="utf-8",
    )


def write_rows(path: Path, header: Iterable[str], rows: list[list[object]]) -> None:
    with path.open("w", newline="") as stream:
        writer = csv.writer(stream)
        writer.writerow(list(header))
        writer.writerows(rows)


def replicate_names() -> list[str]:
    if not RF_ROOT.exists() or not DF_ROOT.exists():
        raise FileNotFoundError(
            "Replicate-ensemble output directories are missing.\n"
            "Run: bash analysis/scripts/run_paper2.sh hysteresis-ensemble 30"
        )
    rf = {
        p.name for p in RF_ROOT.glob("rep_*")
        if (p / "hysteresis_loop.csv").exists()
    }
    df = {
        p.name for p in DF_ROOT.glob("rep_*")
        if (p / "hysteresis_loop.csv").exists()
    }
    common = sorted(rf & df)
    if not common:
        raise RuntimeError(
            "No matched RF/DF hysteresis replicate pairs were found.\n"
            "Run: bash analysis/scripts/run_paper2.sh hysteresis-ensemble 30"
        )
    if rf != df:
        print(
            "Warning: unmatched replicate directories were ignored; "
            f"RF-only={sorted(rf-df)}, DF-only={sorted(df-rf)}"
        )
    return common


def binned_mean(
    target: np.ndarray,
    values: np.ndarray,
    directions: np.ndarray,
    branch: str,
    edges: np.ndarray,
) -> np.ndarray:
    mask = directions == branch
    x = np.asarray(target[mask], dtype=float)
    y = np.asarray(values[mask], dtype=float)
    out = np.full(len(edges) - 1, np.nan, dtype=float)

    for i in range(len(out)):
        if i == len(out) - 1:
            in_bin = (x >= edges[i]) & (x <= edges[i + 1])
        else:
            in_bin = (x >= edges[i]) & (x < edges[i + 1])
        if np.any(in_bin):
            out[i] = np.mean(y[in_bin])
    return out


def ensemble_stats(matrix: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    valid_n = np.sum(np.isfinite(matrix), axis=0)
    mean = np.nanmean(matrix, axis=0)
    sd = np.nanstd(matrix, axis=0, ddof=1)
    sem = sd / np.sqrt(valid_n)
    ci95 = 1.96 * sem
    ci95[valid_n < 2] = np.nan
    return mean, sd, ci95, valid_n


def finite_trapz(y: np.ndarray, x: np.ndarray) -> float:
    mask = np.isfinite(y) & np.isfinite(x)
    if np.sum(mask) < 2:
        return np.nan
    return float(np.trapezoid(y[mask], x[mask]))


def mean_ci95(values: np.ndarray) -> tuple[float, float, float, int]:
    x = np.asarray(values, dtype=float)
    x = x[np.isfinite(x)]
    n = len(x)
    if n == 0:
        return np.nan, np.nan, np.nan, 0
    mean = float(np.mean(x))
    if n < 2:
        return mean, np.nan, np.nan, n
    sd = float(np.std(x, ddof=1))
    ci = float(1.96 * sd / np.sqrt(n))
    return mean, sd, ci, n


def main() -> None:
    reps = replicate_names()
    print(f"Matched RF/DF hysteresis replicate pairs found: {len(reps)}")

    # Obtain a common S* range from all matched replicates and orderings.
    target_arrays = []
    raw = {}
    for tag, _, folder in ORDERINGS:
        raw[tag] = {}
        for rep in reps:
            data = load_csv(folder / rep / "hysteresis_loop.csv")
            raw[tag][rep] = data
            target_arrays.append(np.asarray(data["targetEntropy"], dtype=float))

    all_target = np.concatenate(target_arrays)
    edges = np.linspace(float(np.nanmin(all_target)), float(np.nanmax(all_target)), N_BINS + 1)
    centers = 0.5 * (edges[:-1] + edges[1:])

    # matrices[tag][observable][branch] -> nRep x nBins replicate-binned means.
    matrices: dict[str, dict[str, dict[str, np.ndarray]]] = {}
    for tag, _, _ in ORDERINGS:
        matrices[tag] = {"mu": {}, "dC": {}}
        for observable in ["mu", "dC"]:
            for branch, _, _ in BRANCHES:
                curves = []
                for rep in reps:
                    data = raw[tag][rep]
                    curves.append(
                        binned_mean(
                            np.asarray(data["targetEntropy"], dtype=float),
                            np.asarray(data[observable], dtype=float),
                            np.asarray(data["direction"]),
                            branch,
                            edges,
                        )
                    )
                matrices[tag][observable][branch] = np.vstack(curves)

    branch_curve_rows: list[list[object]] = []
    computed_stats = {}
    for tag, label, _ in ORDERINGS:
        computed_stats[tag] = {}
        for observable in ["mu", "dC"]:
            computed_stats[tag][observable] = {}
            for branch, branch_label, _ in BRANCHES:
                mean, sd, ci95, n = ensemble_stats(matrices[tag][observable][branch])
                computed_stats[tag][observable][branch] = (mean, sd, ci95, n)
                for i, center in enumerate(centers):
                    branch_curve_rows.append([
                        tag, label, branch, branch_label, observable, center,
                        int(n[i]), mean[i], sd[i], ci95[i]
                    ])

    write_rows(
        SUMMARY / "hysteresis_ensemble_branch_curves.csv",
        [
            "ordering", "ordering_label", "branch", "branch_label", "observable",
            "targetEntropy_bin_center", "n_replicates", "mean", "sd_across_replicates",
            "ci95_half_width"
        ],
        branch_curve_rows,
    )

    # Plot ensemble mean and 95% CI bands. Use ordering color and branch line style.
    colors = {"rf": "tab:blue", "df": "tab:orange"}
    observables = [
        ("mu", r"Ensemble mean regulation gain $\langle\mu\rangle$",
         "Replicate-averaged carryover in adaptive regulation",
         "paper2_hysteresis_mu_ensemble_RF_DF.png"),
        ("dC", r"Ensemble mean coherence gap $\langle\Delta C\rangle$",
         "Replicate-averaged continuous-ramp hysteresis: coherence-gap response",
         "paper2_hysteresis_coherence_ensemble_RF_DF.png"),
    ]

    for observable, ylabel, title, filename in observables:
        fig, ax = plt.subplots(figsize=(8.4, 5.4))
        for tag, label, _ in ORDERINGS:
            for branch, branch_label, linestyle in BRANCHES:
                mean, _, ci95, n = computed_stats[tag][observable][branch]
                ok = np.isfinite(mean) & (n > 0)
                ci_ok = ok & np.isfinite(ci95)
                ax.plot(
                    centers[ok], mean[ok],
                    color=colors[tag],
                    linestyle=linestyle,
                    linewidth=2.1,
                    label=f"{label}: {branch_label}",
                )
                if np.any(ci_ok):
                    ax.fill_between(
                        centers[ci_ok],
                        mean[ci_ok] - ci95[ci_ok],
                        mean[ci_ok] + ci95[ci_ok],
                        color=colors[tag],
                        alpha=0.12,
                        linewidth=0,
                    )
        ax.set_xlabel(r"Target entropy $S^*$")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.legend(fontsize=8.6, ncol=2, loc="upper center", bbox_to_anchor=(0.5, -0.16))
        fig.tight_layout()
        fig.savefig(FIG / filename, dpi=300, bbox_inches="tight")
        plt.close(fig)

    # Per-replicate hysteresis-loop areas and paired RF/DF differences.
    per_rep_rows: list[list[object]] = []
    area_values: dict[str, dict[str, np.ndarray]] = {
        observable: {"rf": [], "df": []} for observable in ["mu", "dC"]
    }
    mean_level_values: dict[str, dict[str, np.ndarray]] = {
        observable: {"rf": [], "df": []} for observable in ["mu", "dC"]
    }

    for observable in ["mu", "dC"]:
        for r_index, rep in enumerate(reps):
            for tag, _, _ in ORDERINGS:
                up = matrices[tag][observable]["up"][r_index]
                down = matrices[tag][observable]["down"][r_index]
                area = finite_trapz(down - up, centers)
                level = float(np.nanmean(np.concatenate([up, down])))
                area_values[observable][tag].append(area)
                mean_level_values[observable][tag].append(level)
                per_rep_rows.append([rep, tag, observable, area, level])

    write_rows(
        SUMMARY / "hysteresis_ensemble_per_replicate.csv",
        ["replicate", "ordering", "observable", "signed_area_down_minus_up", "branch_pooled_mean"],
        per_rep_rows,
    )

    summary_rows: list[list[object]] = []
    for observable in ["mu", "dC"]:
        for metric_name, container in [
            ("signed_area_down_minus_up", area_values),
            ("branch_pooled_mean", mean_level_values),
        ]:
            rf = np.asarray(container[observable]["rf"], dtype=float)
            df = np.asarray(container[observable]["df"], dtype=float)
            diff = df - rf
            for tag, values in [("rf", rf), ("df", df), ("paired_df_minus_rf", diff)]:
                mean, sd, ci, n = mean_ci95(values)
                summary_rows.append([observable, metric_name, tag, n, mean, sd, ci])

    write_rows(
        SUMMARY / "hysteresis_ensemble_statistical_summary.csv",
        ["observable", "metric", "comparison", "n", "mean", "sd", "ci95_half_width"],
        summary_rows,
    )

    print(f"Wrote ensemble hysteresis figures to: {FIG}")
    print(f"Wrote ensemble hysteresis numerical summaries to: {SUMMARY}")
    print("Uncertainty bands: approximate 95% confidence intervals, 1.96 * SEM,")
    print("computed across matched-seed replicate-level binned branch curves.")


if __name__ == "__main__":
    main()
