/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package org.iram.omega.iram_omega_q.noise;

/**
 *
 * @author veronique
 */
/**
 * InducedNoiseModel
 *
 * Models disturbance that is generated by the regulatory process itself.
 *
 * This is different from external noise, which comes from the environment,
 * and different from self-generated noise, which comes from autonomous
 * internal fluctuations. Here, the disturbance is caused by abrupt increases
 * in the regulation level mu.
 *
 * Mathematical form:
 *
 *     eta_induced(t) = alpha * max(0, mu(t) - mu(t - 1))^2
 *
 * Only positive changes in mu contribute. In other words, sudden tightening
 * of regulation can induce disturbance, but relaxation of regulation does not.
 *
 * This captures the idea that abrupt corrective effort may itself destabilize
 * the agent.
 */
public final class InducedNoiseModel implements NoiseModel {

    /**
     * Strength of the induced-noise effect.
     *
     * Larger alpha makes abrupt increases in mu produce larger disturbance.
     *
     * Because delta-mu may be numerically small, alpha may need to be much
     * larger than ordinary external-noise amplitudes in order to produce a
     * visible effect.
     */
    private final double alpha;

    /**
     * Construct an induced-noise model.
     *
     * @param alpha non-negative scaling factor for regulation-induced noise
     */
    public InducedNoiseModel(double alpha) {
        if (!Double.isFinite(alpha) || alpha < 0.0) {
            throw new IllegalArgumentException(
                    "alpha must be finite and non-negative");
        }

        this.alpha = alpha;
    }

    /**
     * Return the noise induced by abrupt regulatory tightening.
     *
     * The relevant quantity is the positive part of the change in mu:
     *
     *     dmuPlus = max(0, mu(t) - mu(t - 1))
     *
     * If mu increases, the model adds induced noise proportional to dmuPlus^2.
     * If mu stays the same or decreases, no induced noise is added.
     *
     * @param ctx current noise context containing mu and previousMu
     * @return non-negative induced disturbance amplitude
     */
    /**
    * Preserve the legacy meaning of noiseAt(...): this model's total
    * contribution is its induced-noise contribution.
    */
    @Override
    public double noiseAt(NoiseContext ctx) {
       return inducedNoiseAt(ctx);
    }

   /**
    * This model has no external or autonomous internal component.
    */
    @Override
    public double nonInducedNoiseAt(NoiseContext ctx) {
       return 0.0;
    }

    /**
     * Immediate Option B control-generated disturbance.
     *
     * The context contains μ before and after the controller update in the
     * current cycle. Only positive tightening contributes.
     */
    @Override
    public double inducedNoiseAt(NoiseContext ctx) {
        double dmuPlus = Math.max(0.0, ctx.mu - ctx.previousMu);
        double etaInduced = alpha * dmuPlus * dmuPlus;

        return NoiseModel.requireValidEta(etaInduced);
    }

    /**
     * Return the induced-noise scale factor.
     *
     * Useful for logging simulation configuration.
     *
     * @return alpha
     */
    public double getAlpha() {
        return alpha;
    }
}