/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Interface.java to edit this template
 */
package org.iram.omega.iram_omega_q.noise;

/**
 *
 * @author veronique
 */
/**
 * NoiseModel
 *
 * Defines a source of disturbance for the IRAM-Ω-Q agent.
 *
 * The purpose of this interface is to separate "where noise comes from"
 * from the agent's RF/DF control-ordering logic.
 *
 * A NoiseModel may represent:
 *
 *   - external environmental disturbance;
 *   - self-generated internal disturbance;
 *   - regulation-induced disturbance;
 *   - a composite of several disturbance sources.
 *
 * The model returns only the disturbance amplitude eta(t). It should not
 * directly modify the agent's quantum cognitive state. The agent remains
 * responsible for applying decoherence through DecoherenceModel.apply(...).
 */
public interface NoiseModel {

    /**
     * Return the disturbance amplitude eta(t) at the current simulation step.
     *
     * This method should not directly modify the agent state.
     * It only reports how much disturbance should be applied.
     *
     * @param ctx contextual information available to the noise model
     * @return non-negative finite disturbance amplitude eta(t)
     */
    double noiseAt(NoiseContext ctx);

    /**
    * Return disturbance that is not generated by the current controller update:
    * external noise and autonomous internal noise.
    *
    * Existing noise models remain compatible because, by default, their full
    * noiseAt(...) value is treated as non-induced disturbance.
    */
    default double nonInducedNoiseAt(NoiseContext ctx) {
       return noiseAt(ctx);
    }

   /**
    * Return disturbance generated by a positive same-cycle control increase.
    *
    * Ordinary external and self-generated noise models contribute zero here.
    */
    default double inducedNoiseAt(NoiseContext ctx) {
       return 0.0;
    }
    /**
     * Optional reset hook for stateful noise models.
     *
     * Stateless models can ignore this.
     *
     * Stateful models, such as self-generated internal noise with its own
     * autoregressive variable zeta(t), should use this method to reset their
     * internal random number generator and internal state.
     *
     * @param seed seed used to reset the noise model
     */
    default void reset(long seed) {
        // Default: no internal state to reset.
    }

    /**
     * Human-readable model name for logging and CSV output.
     *
     * Implementing classes may override this to return names such as:
     *
     *   "EXTERNAL"
     *   "SELF_GENERATED"
     *   "INDUCED_TIGHTENING"
     *   "COMPOSITE"
     *
     * @return noise model name
     */
    default String name() {
        return getClass().getSimpleName();
    }

    /**
     * Helper method for validating eta(t).
     *
     * This is useful in implementations before returning a value.
     *
     * @param eta proposed disturbance amplitude
     * @return eta if it is finite and non-negative
     * @throws IllegalStateException if eta is invalid
     */
    static double requireValidEta(double eta) {
        if (!Double.isFinite(eta) || eta < 0.0) {
            throw new IllegalStateException(
                    "NoiseModel returned invalid eta: " + eta);
        }
        return eta;
    }
}