/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package org.iram.omega.iram_omega_q.noise;
import java.util.Random;
/**
 *
 * @author veronique
 */
/**
 * SelfGeneratedNoiseModel
 *
 * Models internally generated disturbance as a persistent stochastic process.
 *
 * This is different from external noise, which represents disturbance arriving
 * from the environment, and different from induced noise, which is generated by
 * the controller itself. Here, the disturbance comes from the agent's own
 * internal dynamics.
 *
 * Mathematically, the model evolves an internal noise state:
 *
 *     zeta(t + 1) = rho * zeta(t) + sigmaIn * epsilon(t)
 *
 * where epsilon(t) is a standard Gaussian random variable.
 *
 * The returned disturbance amplitude is:
 *
 *     eta_self(t) = |zeta(t)|
 *
 * The absolute value is used because DecoherenceModel.apply(...) expects a
 * non-negative disturbance amplitude.
 */
public final class SelfGeneratedNoiseModel implements NoiseModel {

    /**
     * Persistence of the internal noise process.
     *
     * rho close to 0 means the internal disturbance is almost memoryless.
     * rho close to 1 means the disturbance persists over many time steps.
     *
     * For stability, typical values should satisfy |rho| < 1.
     */
    private final double rho;

    /**
     * Strength of the random innovation added at each step.
     *
     * Larger sigmaIn produces stronger self-generated fluctuations.
     */
    private final double sigmaIn;

    /**
     * Random number generator used to produce the Gaussian innovation epsilon(t).
     *
     * This RNG is separate from the agent RNG so that self-generated noise can
     * be seeded and reproduced independently.
     */
    private Random rng;

    /**
     * Current internal noise state.
     *
     * zeta may be positive or negative. The sign is part of the internal
     * stochastic process, but the returned disturbance amplitude is |zeta|.
     */
    private double zeta;

    /**
     * Construct a persistent self-generated noise model.
     *
     * @param rho persistence coefficient of the internal noise state
     * @param sigmaIn innovation strength
     * @param seed seed for reproducible internal-noise trajectories
     */
    public SelfGeneratedNoiseModel(double rho, double sigmaIn, long seed) {
        if (!Double.isFinite(rho) || Math.abs(rho) >= 1.0) {
            throw new IllegalArgumentException(
                    "rho must be finite with |rho| < 1");
        }
        if (!Double.isFinite(sigmaIn) || sigmaIn < 0.0) {
            throw new IllegalArgumentException(
                    "sigmaIn must be finite and non-negative");
        }

        this.rho = rho;
        this.sigmaIn = sigmaIn;
        reset(seed);
    }

    /**
     * Reset the internal-noise process.
     *
     * This restores zeta to zero and reinitializes the random number generator.
     * Use this when beginning a new simulation run so that repeated runs are
     * reproducible under fixed seeds.
     *
     * @param seed seed for the internal noise RNG
     */
    @Override
    public void reset(long seed) {
        this.rng = new Random(seed);
        this.zeta = 0.0;
    }

    /**
     * Advance the internal-noise process by one step and return its amplitude.
     *
     * The context is not used in this simple model because the self-generated
     * noise evolves autonomously. It is included in the method signature because
     * other NoiseModel implementations may depend on mu, deltaMu, time, or other
     * contextual quantities.
     *
     * @param ctx current noise context
     * @return non-negative self-generated disturbance amplitude |zeta(t)|
     */
    @Override
    public double noiseAt(NoiseContext ctx) {
        zeta = rho * zeta + sigmaIn * rng.nextGaussian();

        double etaSelf = Math.abs(zeta);
        return NoiseModel.requireValidEta(etaSelf);
    }

    /**
     * Return the signed internal noise state.
     *
     * This is useful for diagnostics and plotting. The signed value shows the
     * internal stochastic process before it is converted into a non-negative
     * disturbance amplitude.
     *
     * @return current signed zeta value
     */
    public double currentZeta() {
        return zeta;
    }
}